---
title: "Calculate Effect size for visits in Sputum and create combined figure across all phylogenetic levels"
author: "Rebecca L. Knoll"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages and colors, include=FALSE}

pacman::p_load(tidyverse, phyloseq, microbiome, knitr, lubridate, ggplotify, gtools, ggplot2, ggpubr, microViz, metadeconfoundR)

```

```{r prepare data}
# use ps for sputum samples only
ps_full <- readRDS("/Users/rebecca/Documents/Forschung/IMMProveCF/R_analysis/rds_files/ps_full_IMP.rds")
# subset per materialfor
ps_full_sputum <- subset_samples(ps_full, material== "Sputum")

# calculate relative abundances
ps_sputum_relab <- transform_sample_counts(ps_full_sputum, function(x) x/sum(x))
ps_sputum_relab <-prune_taxa(taxa_sums(ps_sputum_relab) > 0.40, ps_sputum_relab) # > 40% prevalence over all samples, 24 most abundant genera

ps_sputum_relab_family <- tax_glom(ps_sputum_relab, "Family")
ps_sputum_relab_order <- tax_glom(ps_sputum_relab, "Order")
ps_sputum_relab_class <- tax_glom(ps_sputum_relab, "Class")
ps_sputum_relab_phylum<- tax_glom(ps_sputum_relab, "Phylum")
```

# ASV/Genus level
```{r MetadeconfoundR V1vsV2}
psV1V2 <-
 phyloseq::subset_samples(ps_sputum_relab , visit.x  %in% c("V1", "V2"))

metadata_V1V2 <- as(sample_data(psV1V2),"data.frame")

metada <- metadata_V1V2%>%
  mutate(visit_V1V2 = (as.numeric(visit.x))-1)

metada<- cbind(visit_V1V2 =metada$visit_V1V2, subset(metada,select = -c(visit_V1V2))) # brings visit into the first column

metada <- metada%>%
  select(visit_V1V2, id)

# run metadeconfoundR
features <- as.data.frame(otu_table(psV1V2))
taxtable <- as.data.frame(tax_table(psV1V2))

#create two-column-dataframe containing corresponding "human-readable" names to the "machine-readable" feature names used as row.names in metaDeconfOutput.  
taxtable <- taxtable%>%
  select(Genus)
taxtable$ASV <- row.names(taxtable)
taxtable<- cbind(ASV=taxtable$ASV,subset(taxtable,select = -c(ASV)))

### run it
metad <- MetaDeconfound(featureMat = features, metaMat = metada, randomVar =  c("id"),  nnodes=9)

raw_p_V1V2 <- metad[1]
corr_p_V1V2 <- metad[2]
effect_size_V1V2 <- metad[3]
status_V1V2 <- metad[4]
```

```{r MetadeconfoundR V1vsV3-V5}
psV1_V3V5 <-
 phyloseq::subset_samples(ps_sputum_relab , visit_cal_cor  %in% c("1", "3", "4", "5"))

metadata_V1_V3V5 <- as(sample_data(psV1_V3V5),"data.frame")

metadata_V1_V3V5$visit_cal_cor
metadata_V1_V3V5$visit_sum

metada <- metadata_V1_V3V5%>%
  mutate(visit_V1_V3V5 = (as.numeric(visit_sum))-1)

metada<- cbind(visit_V1_V3V5 =metada$visit_V1_V3V5, subset(metada,select = -c(visit_V1_V3V5))) # brings visit into the first column

metada <- metada%>%
  select(visit_V1_V3V5, id)

# run metadeconfoundR
features <- as.data.frame(otu_table(psV1_V3V5))
taxtable <- as.data.frame(tax_table(psV1_V3V5))

#create two-column-dataframe containing corresponding "human-readable" names to the "machine-readable" feature names used as row.names in metaDeconfOutput.  
taxtable <- taxtable%>%
  select(Genus)
taxtable$ASV <- row.names(taxtable)
taxtable<- cbind(ASV=taxtable$ASV,subset(taxtable,select = -c(ASV)))

### run it
metad <- MetaDeconfound(featureMat = features, metaMat = metada, randomVar = c("id"),  nnodes=9)

raw_pV1_V3V5 <- metad[1]
corr_pV1_V3V5 <- metad[2]
effect_sizeV1_V3V5 <- metad[3]
statusV1_V3V5 <- metad[4]

```
```{r MetadeconfoundR V1vsV6-V7}
psV1_V6V7 <-
 phyloseq::subset_samples(ps_sputum_relab , visit_cal_cor  %in% c("1", "6", "7"))

metadata_V1_V6V7 <- as(sample_data(psV1_V6V7),"data.frame")

metadata_V1_V6V7$visit_cal_cor
metadata_V1_V6V7$visit_sum

metada <- metadata_V1_V6V7%>%
  mutate(visit_V1_V6V7 = (as.numeric(visit_sum))-1)

metada<- cbind(visit_V1_V6V7 =metada$visit_V1_V6V7, subset(metada,select = -c(visit_V1_V6V7))) # brings visit into the first column

metada <- metada%>%
  select(visit_V1_V6V7, id)

# run metadeconfoundR
features <- as.data.frame(otu_table(psV1_V6V7))
taxtable <- as.data.frame(tax_table(psV1_V6V7))

#create two-column-dataframe containing corresponding "human-readable" names to the "machine-readable" feature names used as row.names in metaDeconfOutput.  
taxtable <- taxtable%>%
  select(Genus)
taxtable$ASV <- row.names(taxtable)
taxtable<- cbind(ASV=taxtable$ASV,subset(taxtable,select = -c(ASV)))

### run it
metad <- MetaDeconfound(featureMat = features, metaMat = metada, randomVar = c("id"),  nnodes=9)

raw_p_V1_V6V7 <- metad[1]
corr_p_V1_V6V7 <- metad[2]
effect_size_V1_V6V7 <- metad[3]
status_V1_V6V7 <- metad[4]
```

```{r MetadeconfoundR V1vsV8-V9}
psV1_V8V9 <-
 phyloseq::subset_samples(ps_sputum_relab , visit_cal_cor  %in% c("1", "8", "9"))

metadata_V1_V8V9 <- as(sample_data(psV1_V8V9),"data.frame")

metadata_V1_V8V9$visit_cal_cor
metadata_V1_V8V9$visit_sum

metada <- metadata_V1_V8V9%>%
  mutate(visitV1_V8V9 = (as.numeric(visit_sum))-1)

metada<- cbind(visitV1_V8V9 =metada$visitV1_V8V9, subset(metada,select = -c(visitV1_V8V9))) # brings visit into the first column

metada <- metada%>%
  select(visitV1_V8V9, id)

# run metadeconfoundR
features <- as.data.frame(otu_table(psV1_V8V9))
taxtable <- as.data.frame(tax_table(psV1_V8V9))

#create two-column-dataframe containing corresponding "human-readable" names to the "machine-readable" feature names used as row.names in metaDeconfOutput.  
taxtable <- taxtable%>%
  select(Genus)
taxtable$ASV <- row.names(taxtable)
taxtable<- cbind(ASV=taxtable$ASV,subset(taxtable,select = -c(ASV)))

### run it
metad <- MetaDeconfound(featureMat = features, metaMat = metada, randomVar = c("id"),  nnodes=9)

raw_p_V1_V8V9 <- metad[1]
corr_p_V1_V8V9 <- metad[2]
effect_size_V1_V8V9 <- metad[3]
status_V1_V8V9 <- metad[4]
```

```{r bind effectsize table}

raw_p <- purrr::map2(raw_p_V1V2,raw_pV1_V3V5,cbind)
raw_p <- purrr::map2(raw_p,raw_p_V1_V6V7,cbind)
raw_p <- purrr::map2(raw_p,raw_p_V1_V8V9,cbind)

raw_p_df <- bind_rows(raw_p)
raw_p_df <- data.frame(raw_p_df$Ps)
raw_p_df  <- raw_p_df %>%
  rownames_to_column()%>%
  mutate(p_V1_V2=visit_V1V2)%>%
  mutate(p_V1_V3V5=visit_V1_V3V5)%>%
  mutate(p_V1_V6V7=visit_V1_V6V7)%>%
  mutate(p_V1_V8V9=visitV1_V8V9)%>%
  mutate(ASV=rowname)%>%
  select(-c(1:9))

corr_p <- purrr::map2(corr_p_V1V2,corr_pV1_V3V5,cbind)
corr_p <- purrr::map2(corr_p,corr_p_V1_V6V7,cbind)
corr_p <- purrr::map2(corr_p,corr_p_V1_V8V9,cbind)

corr_p_df <- bind_rows(corr_p)
corr_p_df <- data.frame(corr_p_df$Qs)
corr_p_df  <- corr_p_df %>%
  rownames_to_column()%>%
  mutate(q_V1_V2=visit_V1V2)%>%
  mutate(q_V1_V3V5=visit_V1_V3V5)%>%
  mutate(q_V1_V6V7=visit_V1_V6V7)%>%
  mutate(q_V1_V8V9=visitV1_V8V9)%>%
  mutate(ASV=rowname)%>%
  select(-c(1:9))

effect_size <- purrr::map2(effect_size_V1V2,effect_sizeV1_V3V5,cbind)
effect_size <- purrr::map2(effect_size,effect_size_V1_V6V7,cbind)
effect_size <- purrr::map2(effect_size,effect_size_V1_V8V9,cbind)

effect_size_df <- bind_rows(effect_size)
effect_size_df <- data.frame(effect_size_df$Ds)
effect_size_df  <- effect_size_df %>%
  rownames_to_column()%>%
  mutate(d_V1_V2=visit_V1V2)%>%
  mutate(d_V1_V3V5=visit_V1_V3V5)%>%
  mutate(d_V1_V6V7=visit_V1_V6V7)%>%
  mutate(d_V1_V8V9=visitV1_V8V9)%>%
  mutate(ASV=rowname)%>%
  select(-c(1:9))


status <- purrr::map2(status_V1V2,statusV1_V3V5,cbind)
status <- purrr::map2(status,status_V1_V6V7,cbind)
status <- purrr::map2(status,status_V1_V8V9,cbind)

status_df <- bind_rows(status)
status_df <- data.frame(status_df$status)
status_df  <- status_df %>%
  rownames_to_column()%>%
  mutate(status_V1_V2=visit_V1V2)%>%
  mutate(status_V1_V3V5=visit_V1_V3V5)%>%
  mutate(status_V1_V6V7=visit_V1_V6V7)%>%
  mutate(status_V1_V8V9=visitV1_V8V9)%>%
  mutate(ASV=rowname)%>%
  select(-c(1:9))

effect_table <- raw_p_df%>%
  full_join(corr_p_df, by="ASV")%>%
  full_join(effect_size_df, by="ASV")%>%
  full_join(status_df, by="ASV")%>%
  full_join(taxtable, by="ASV")

# select the entries which have OK_nc in status
effect_table_sig <- effect_table%>%
  filter(status_V1_V2=="OK_nc"|status_V1_V3V5=="OK_nc"|status_V1_V6V7 =="OK_nc" | status_V1_V8V9=="OK_nc")

#pivot long format

effect_table_sig_long <- effect_table_sig%>%
  pivot_longer(cols = starts_with("status"), names_to = "comparison_status", values_to = "status")%>%
  separate(comparison_status, c("variable","Visit1", "Visit_Sum"), "_")%>%
  mutate(comparison_status=paste(Visit1,Visit_Sum, sep="_"))%>%
  select(-c(variable, Visit1, Visit_Sum))%>%
  pivot_longer(cols = starts_with("p"), names_to = "comparison_p", values_to = "raw_p")%>%
  separate(comparison_p, c("variable","Visit1", "Visit_Sum"), "_")%>%
  mutate(comparison_p=paste(Visit1,Visit_Sum, sep="_"))%>%
  select(-c(variable, Visit1, Visit_Sum))%>%
  filter(comparison_p==comparison_status)%>%
  pivot_longer(cols = starts_with("d"), names_to = "comparison_effectSize", values_to = "effectSize")%>%
  separate(comparison_effectSize, c("variable","Visit1", "Visit_Sum"), "_")%>%
  mutate(comparison_effectSize=paste(Visit1,Visit_Sum, sep="_"))%>%
  select(-c(variable, Visit1, Visit_Sum))%>%
  filter(comparison_p==comparison_effectSize)%>%
  pivot_longer(cols = starts_with("q"), names_to = "comparison_q", values_to = "corr_p")%>%
  separate(comparison_q, c("variable","Visit1", "Visit_Sum"), "_")%>%
  mutate(comparison_q=paste(Visit1,Visit_Sum, sep="_"))%>%
  select(-c(variable, Visit1, Visit_Sum))%>%
  filter(comparison_p==comparison_q)%>%
  select(-c(comparison_q, comparison_effectSize,comparison_status))%>%
  mutate(fdr= as_factor(case_when(corr_p <= 0.05 ~ "*", corr_p <= 0.01 ~ "**", corr_p <= 0.001 ~ "***", corr_p <= 0.1 ~ ".")))%>%
  mutate(taxa=paste(Genus, "(Genus)"))%>%
  select(-Genus)

```

```{r plot cuneiform }
effect_table_sig_long%>%
  ggplot(aes (x = comparison_p, y = taxa))+ 
  geom_point (aes (fill = effectSize, shape = as.factor (sign (effectSize)), size = abs (effectSize), color=(fdr))) +
  scale_shape_manual (values = c (25, 24)) + 
  scale_fill_gradient2 (low = "blue", high = "red", mid = "white", midpoint = 0) +
  scale_color_manual(values=c("gray22","gray1","gray85"))+
  geom_text (aes (label = stars.pval (corr_p)))+
  theme_grey() +
  theme(axis.text.x = element_text(), #angle = 0, hjust = 0, vjust = 1
       legend.position = "right",axis.text.y = element_text(face = "italic"))+
  scale_x_discrete(labels=c("3", "6-12", "15-18", "21-24"))+
  labs(x= "months from treatment start")
```
# Family level

```{r MetadeconfoundR V1vsV2 family}
psV1V2 <-
 phyloseq::subset_samples(ps_sputum_relab_family , visit.x  %in% c("V1", "V2"))

metadata_V1V2 <- as(sample_data(psV1V2),"data.frame")

metada <- metadata_V1V2%>%
  mutate(visit_V1V2 = (as.numeric(visit.x))-1)

metada<- cbind(visit_V1V2 =metada$visit_V1V2, subset(metada,select = -c(visit_V1V2))) # brings visit into the first column

metada <- metada%>%
  select(visit_V1V2, id)

# run metadeconfoundR
features <- as.data.frame(otu_table(psV1V2))
taxtable <- as.data.frame(tax_table(psV1V2))

#create two-column-dataframe containing corresponding "human-readable" names to the "machine-readable" feature names used as row.names in metaDeconfOutput.  
taxtable <- taxtable%>%
  select(Family)
taxtable$ASV <- row.names(taxtable)
taxtable<- cbind(ASV=taxtable$ASV,subset(taxtable,select = -c(ASV)))

### run it
metad <- MetaDeconfound(featureMat = features, metaMat = metada, randomVar = c("id"),  nnodes=9)

raw_p_V1V2 <- metad[1]
corr_p_V1V2 <- metad[2]
effect_size_V1V2 <- metad[3]
status_V1V2 <- metad[4]
```

```{r MetadeconfoundR V1vsV3-V5 family}
psV1_V3V5 <-
 phyloseq::subset_samples(ps_sputum_relab_family , visit_cal_cor  %in% c("1", "3", "4", "5"))

metadata_V1_V3V5 <- as(sample_data(psV1_V3V5),"data.frame")

metadata_V1_V3V5$visit_cal_cor
metadata_V1_V3V5$visit_sum

metada <- metadata_V1_V3V5%>%
  mutate(visit_V1_V3V5 = (as.numeric(visit_sum))-1)

metada<- cbind(visit_V1_V3V5 =metada$visit_V1_V3V5, subset(metada,select = -c(visit_V1_V3V5))) # brings visit into the first column

metada <- metada%>%
  select(visit_V1_V3V5, id)

# run metadeconfoundR
features <- as.data.frame(otu_table(psV1_V3V5))
taxtable <- as.data.frame(tax_table(psV1_V3V5))

#create two-column-dataframe containing corresponding "human-readable" names to the "machine-readable" feature names used as row.names in metaDeconfOutput.  
taxtable <- taxtable%>%
  select(Family)
taxtable$ASV <- row.names(taxtable)
taxtable<- cbind(ASV=taxtable$ASV,subset(taxtable,select = -c(ASV)))

### run it
metad <- MetaDeconfound(featureMat = features, metaMat = metada, randomVar = c("id"),  nnodes=9)

raw_pV1_V3V5 <- metad[1]
corr_pV1_V3V5 <- metad[2]
effect_sizeV1_V3V5 <- metad[3]
statusV1_V3V5 <- metad[4]
```
```{r MetadeconfoundR V1vsV6-V7 family}
psV1_V6V7 <-
 phyloseq::subset_samples(ps_sputum_relab_family , visit_cal_cor  %in% c("1", "6", "7"))

metadata_V1_V6V7 <- as(sample_data(psV1_V6V7),"data.frame")

metadata_V1_V6V7$visit_cal_cor
metadata_V1_V6V7$visit_sum

metada <- metadata_V1_V6V7%>%
  mutate(visit_V1_V6V7 = (as.numeric(visit_sum))-1)

metada<- cbind(visit_V1_V6V7 =metada$visit_V1_V6V7, subset(metada,select = -c(visit_V1_V6V7))) # brings visit into the first column

metada <- metada%>%
  select(visit_V1_V6V7, id)

# run metadeconfoundR
features <- as.data.frame(otu_table(psV1_V6V7))
taxtable <- as.data.frame(tax_table(psV1_V6V7))

#create two-column-dataframe containing corresponding "human-readable" names to the "machine-readable" feature names used as row.names in metaDeconfOutput.  
taxtable <- taxtable%>%
  select(Family)
taxtable$ASV <- row.names(taxtable)
taxtable<- cbind(ASV=taxtable$ASV,subset(taxtable,select = -c(ASV)))

### run it
metad <- MetaDeconfound(featureMat = features, metaMat = metada, randomVar = c("id"),  nnodes=9)

raw_p_V1_V6V7 <- metad[1]
corr_p_V1_V6V7 <- metad[2]
effect_size_V1_V6V7 <- metad[3]
status_V1_V6V7 <- metad[4]
```

```{r MetadeconfoundR V1vsV8-V9 family}
psV1_V8V9 <-
 phyloseq::subset_samples(ps_sputum_relab_family, visit_cal_cor  %in% c("1", "8", "9"))

metadata_V1_V8V9 <- as(sample_data(psV1_V8V9),"data.frame")

metadata_V1_V8V9$visit_cal_cor
metadata_V1_V8V9$visit_sum

metada <- metadata_V1_V8V9%>%
  mutate(visitV1_V8V9 = (as.numeric(visit_sum))-1)

metada<- cbind(visitV1_V8V9 =metada$visitV1_V8V9, subset(metada,select = -c(visitV1_V8V9))) # brings visit into the first column

metada <- metada%>%
  select(visitV1_V8V9, id)

# run metadeconfoundR
features <- as.data.frame(otu_table(psV1_V8V9))
taxtable <- as.data.frame(tax_table(psV1_V8V9))

#create two-column-dataframe containing corresponding "human-readable" names to the "machine-readable" feature names used as row.names in metaDeconfOutput.  
taxtable <- taxtable%>%
  select(Family)
taxtable$ASV <- row.names(taxtable)
taxtable<- cbind(ASV=taxtable$ASV,subset(taxtable,select = -c(ASV)))

### run it
metad <- MetaDeconfound(featureMat = features, metaMat = metada, randomVar = c("id"),  nnodes=9)

raw_p_V1_V8V9 <- metad[1]
corr_p_V1_V8V9 <- metad[2]
effect_size_V1_V8V9 <- metad[3]
status_V1_V8V9 <- metad[4]
```

```{r bind effectsize table family}

raw_p <- purrr::map2(raw_p_V1V2,raw_pV1_V3V5,cbind)
raw_p <- purrr::map2(raw_p,raw_p_V1_V6V7,cbind)
raw_p <- purrr::map2(raw_p,raw_p_V1_V8V9,cbind)

raw_p_df <- bind_rows(raw_p)
raw_p_df <- data.frame(raw_p_df$Ps)
raw_p_df  <- raw_p_df %>%
  rownames_to_column()%>%
  mutate(p_V1_V2=visit_V1V2)%>%
  mutate(p_V1_V3V5=visit_V1_V3V5)%>%
  mutate(p_V1_V6V7=visit_V1_V6V7)%>%
  mutate(p_V1_V8V9=visitV1_V8V9)%>%
  mutate(ASV=rowname)%>%
  select(-c(1:9))

corr_p <- purrr::map2(corr_p_V1V2,corr_pV1_V3V5,cbind)
corr_p <- purrr::map2(corr_p,corr_p_V1_V6V7,cbind)
corr_p <- purrr::map2(corr_p,corr_p_V1_V8V9,cbind)

corr_p_df <- bind_rows(corr_p)
corr_p_df <- data.frame(corr_p_df$Qs)
corr_p_df  <- corr_p_df %>%
  rownames_to_column()%>%
  mutate(q_V1_V2=visit_V1V2)%>%
  mutate(q_V1_V3V5=visit_V1_V3V5)%>%
  mutate(q_V1_V6V7=visit_V1_V6V7)%>%
  mutate(q_V1_V8V9=visitV1_V8V9)%>%
  mutate(ASV=rowname)%>%
  select(-c(1:9))

effect_size <- purrr::map2(effect_size_V1V2,effect_sizeV1_V3V5,cbind)
effect_size <- purrr::map2(effect_size,effect_size_V1_V6V7,cbind)
effect_size <- purrr::map2(effect_size,effect_size_V1_V8V9,cbind)

effect_size_df <- bind_rows(effect_size)
effect_size_df <- data.frame(effect_size_df$Ds)
effect_size_df  <- effect_size_df %>%
  rownames_to_column()%>%
  mutate(d_V1_V2=visit_V1V2)%>%
  mutate(d_V1_V3V5=visit_V1_V3V5)%>%
  mutate(d_V1_V6V7=visit_V1_V6V7)%>%
  mutate(d_V1_V8V9=visitV1_V8V9)%>%
  mutate(ASV=rowname)%>%
  select(-c(1:9))


status <- purrr::map2(status_V1V2,statusV1_V3V5,cbind)
status <- purrr::map2(status,status_V1_V6V7,cbind)
status <- purrr::map2(status,status_V1_V8V9,cbind)

status_df <- bind_rows(status)
status_df <- data.frame(status_df$status)
status_df  <- status_df %>%
  rownames_to_column()%>%
  mutate(status_V1_V2=visit_V1V2)%>%
  mutate(status_V1_V3V5=visit_V1_V3V5)%>%
  mutate(status_V1_V6V7=visit_V1_V6V7)%>%
  mutate(status_V1_V8V9=visitV1_V8V9)%>%
  mutate(ASV=rowname)%>%
  select(-c(1:9))

effect_table_family <- raw_p_df%>%
  full_join(corr_p_df, by="ASV")%>%
  full_join(effect_size_df, by="ASV")%>%
  full_join(status_df, by="ASV")%>%
  full_join(taxtable, by="ASV")

# select the entries which have OK_nc in status
effect_table_sig_family <- effect_table_family%>%
  filter(status_V1_V2=="OK_nc"|status_V1_V3V5=="OK_nc"|status_V1_V6V7 =="OK_nc" | status_V1_V8V9=="OK_nc")

#pivot long format

effect_table_sig_long_family <- effect_table_sig_family%>%
  pivot_longer(cols = starts_with("status"), names_to = "comparison_status", values_to = "status")%>%
  separate(comparison_status, c("variable","Visit1", "Visit_Sum"), "_")%>%
  mutate(comparison_status=paste(Visit1,Visit_Sum, sep="_"))%>%
  select(-c(variable, Visit1, Visit_Sum))%>%
  pivot_longer(cols = starts_with("p"), names_to = "comparison_p", values_to = "raw_p")%>%
  separate(comparison_p, c("variable","Visit1", "Visit_Sum"), "_")%>%
  mutate(comparison_p=paste(Visit1,Visit_Sum, sep="_"))%>%
  select(-c(variable, Visit1, Visit_Sum))%>%
  filter(comparison_p==comparison_status)%>%
  pivot_longer(cols = starts_with("d"), names_to = "comparison_effectSize", values_to = "effectSize")%>%
  separate(comparison_effectSize, c("variable","Visit1", "Visit_Sum"), "_")%>%
  mutate(comparison_effectSize=paste(Visit1,Visit_Sum, sep="_"))%>%
  select(-c(variable, Visit1, Visit_Sum))%>%
  filter(comparison_p==comparison_effectSize)%>%
  pivot_longer(cols = starts_with("q"), names_to = "comparison_q", values_to = "corr_p")%>%
  separate(comparison_q, c("variable","Visit1", "Visit_Sum"), "_")%>%
  mutate(comparison_q=paste(Visit1,Visit_Sum, sep="_"))%>%
  select(-c(variable, Visit1, Visit_Sum))%>%
  filter(comparison_p==comparison_q)%>%
  select(-c(comparison_q, comparison_effectSize,comparison_status))%>%
  mutate(fdr= as_factor(case_when(corr_p <= 0.05 ~ "*", corr_p <= 0.01 ~ "**", corr_p <= 0.001 ~ "***", corr_p <= 0.1 ~ ".")))%>%
  mutate(taxa=paste(Family, "(Family)"))%>%
  select(-Family)

```

```{r plot cuneiform family}

effect_table_sig_long_family%>%
  ggplot(aes (x = comparison_p, y = taxa))+ 
  geom_point (aes (fill = effectSize, shape = as.factor (sign (effectSize)), size = abs (effectSize), color=(fdr))) +
  scale_shape_manual (values = c (25, 24)) + 
  scale_fill_gradient2 (low = "blue", high = "red", mid = "white", midpoint = 0) +
  scale_color_manual(values=c("gray22","gray1","gray85"))+
  geom_text (aes (label = stars.pval (corr_p)))+
  theme_grey() +
  theme(axis.text.x = element_text(), #angle = 0, hjust = 0, vjust = 1
       legend.position = "right",axis.text.y = element_text(face = "italic"))+
  scale_x_discrete(labels=c("3", "6-12", "15-18", "21-24"))+
  labs(x= "months from treatment start")
```

# Order level

```{r MetadeconfoundR V1vsV2 order}
psV1V2 <-
 phyloseq::subset_samples(ps_sputum_relab_order , visit.x  %in% c("V1", "V2"))

metadata_V1V2 <- as(sample_data(psV1V2),"data.frame")

metada <- metadata_V1V2%>%
  mutate(visit_V1V2 = (as.numeric(visit.x))-1)

metada<- cbind(visit_V1V2 =metada$visit_V1V2, subset(metada,select = -c(visit_V1V2))) # brings visit into the first column

metada <- metada%>%
  select(visit_V1V2, id)

# run metadeconfoundR
features <- as.data.frame(otu_table(psV1V2))
taxtable <- as.data.frame(tax_table(psV1V2))

#create two-column-dataframe containing corresponding "human-readable" names to the "machine-readable" feature names used as row.names in metaDeconfOutput.  
taxtable <- taxtable%>%
  select(Order)
taxtable$ASV <- row.names(taxtable)
taxtable<- cbind(ASV=taxtable$ASV,subset(taxtable,select = -c(ASV)))

### run it
metad <- MetaDeconfound(featureMat = features, metaMat = metada, randomVar = c("id"),  nnodes=9)

raw_p_V1V2 <- metad[1]
corr_p_V1V2 <- metad[2]
effect_size_V1V2 <- metad[3]
status_V1V2 <- metad[4]
```

```{r MetadeconfoundR V1vsV3-V5 order}
psV1_V3V5 <-
 phyloseq::subset_samples(ps_sputum_relab_order , visit_cal_cor  %in% c("1", "3", "4", "5"))

metadata_V1_V3V5 <- as(sample_data(psV1_V3V5),"data.frame")

metadata_V1_V3V5$visit_cal_cor
metadata_V1_V3V5$visit_sum

metada <- metadata_V1_V3V5%>%
  mutate(visit_V1_V3V5 = (as.numeric(visit_sum))-1)

metada<- cbind(visit_V1_V3V5 =metada$visit_V1_V3V5, subset(metada,select = -c(visit_V1_V3V5))) # brings visit into the first column

metada <- metada%>%
  select(visit_V1_V3V5, id)

# run metadeconfoundR
features <- as.data.frame(otu_table(psV1_V3V5))
taxtable <- as.data.frame(tax_table(psV1_V3V5))

#create two-column-dataframe containing corresponding "human-readable" names to the "machine-readable" feature names used as row.names in metaDeconfOutput.  
taxtable <- taxtable%>%
  select(Order)
taxtable$ASV <- row.names(taxtable)
taxtable<- cbind(ASV=taxtable$ASV,subset(taxtable,select = -c(ASV)))

### run it
metad <- MetaDeconfound(featureMat = features, metaMat = metada, randomVar = c("id"),  nnodes=9)

raw_pV1_V3V5 <- metad[1]
corr_pV1_V3V5 <- metad[2]
effect_sizeV1_V3V5 <- metad[3]
statusV1_V3V5 <- metad[4]
```
```{r MetadeconfoundR V1vsV6-V7 order}
psV1_V6V7 <-
 phyloseq::subset_samples(ps_sputum_relab_order , visit_cal_cor  %in% c("1", "6", "7"))

metadata_V1_V6V7 <- as(sample_data(psV1_V6V7),"data.frame")

metadata_V1_V6V7$visit_cal_cor
metadata_V1_V6V7$visit_sum

metada <- metadata_V1_V6V7%>%
  mutate(visit_V1_V6V7 = (as.numeric(visit_sum))-1)

metada<- cbind(visit_V1_V6V7 =metada$visit_V1_V6V7, subset(metada,select = -c(visit_V1_V6V7))) # brings visit into the first column

metada <- metada%>%
  select(visit_V1_V6V7, id)

# run metadeconfoundR
features <- as.data.frame(otu_table(psV1_V6V7))
taxtable <- as.data.frame(tax_table(psV1_V6V7))

#create two-column-dataframe containing corresponding "human-readable" names to the "machine-readable" feature names used as row.names in metaDeconfOutput.  
taxtable <- taxtable%>%
  select(Order)
taxtable$ASV <- row.names(taxtable)
taxtable<- cbind(ASV=taxtable$ASV,subset(taxtable,select = -c(ASV)))

### run it
metad <- MetaDeconfound(featureMat = features, metaMat = metada, randomVar = c("id"),  nnodes=9)

raw_p_V1_V6V7 <- metad[1]
corr_p_V1_V6V7 <- metad[2]
effect_size_V1_V6V7 <- metad[3]
status_V1_V6V7 <- metad[4]
```

```{r MetadeconfoundR V1vsV8-V9 order}
psV1_V8V9 <-
 phyloseq::subset_samples(ps_sputum_relab_order, visit_cal_cor  %in% c("1", "8", "9"))

metadata_V1_V8V9 <- as(sample_data(psV1_V8V9),"data.frame")

metadata_V1_V8V9$visit_cal_cor
metadata_V1_V8V9$visit_sum

metada <- metadata_V1_V8V9%>%
  mutate(visitV1_V8V9 = (as.numeric(visit_sum))-1)

metada<- cbind(visitV1_V8V9 =metada$visitV1_V8V9, subset(metada,select = -c(visitV1_V8V9))) # brings visit into the first column

metada <- metada%>%
  select(visitV1_V8V9, id)

# run metadeconfoundR
features <- as.data.frame(otu_table(psV1_V8V9))
taxtable <- as.data.frame(tax_table(psV1_V8V9))

#create two-column-dataframe containing corresponding "human-readable" names to the "machine-readable" feature names used as row.names in metaDeconfOutput.  
taxtable <- taxtable%>%
  select(Order)
taxtable$ASV <- row.names(taxtable)
taxtable<- cbind(ASV=taxtable$ASV,subset(taxtable,select = -c(ASV)))

### run it
metad <- MetaDeconfound(featureMat = features, metaMat = metada, randomVar = c("id"),  nnodes=9)

raw_p_V1_V8V9 <- metad[1]
corr_p_V1_V8V9 <- metad[2]
effect_size_V1_V8V9 <- metad[3]
status_V1_V8V9 <- metad[4]
```

```{r bind effectsize table order}

raw_p <- purrr::map2(raw_p_V1V2,raw_pV1_V3V5,cbind)
raw_p <- purrr::map2(raw_p,raw_p_V1_V6V7,cbind)
raw_p <- purrr::map2(raw_p,raw_p_V1_V8V9,cbind)

raw_p_df <- bind_rows(raw_p)
raw_p_df <- data.frame(raw_p_df$Ps)
raw_p_df  <- raw_p_df %>%
  rownames_to_column()%>%
  mutate(p_V1_V2=visit_V1V2)%>%
  mutate(p_V1_V3V5=visit_V1_V3V5)%>%
  mutate(p_V1_V6V7=visit_V1_V6V7)%>%
  mutate(p_V1_V8V9=visitV1_V8V9)%>%
  mutate(ASV=rowname)%>%
  select(-c(1:9))

corr_p <- purrr::map2(corr_p_V1V2,corr_pV1_V3V5,cbind)
corr_p <- purrr::map2(corr_p,corr_p_V1_V6V7,cbind)
corr_p <- purrr::map2(corr_p,corr_p_V1_V8V9,cbind)

corr_p_df <- bind_rows(corr_p)
corr_p_df <- data.frame(corr_p_df$Qs)
corr_p_df  <- corr_p_df %>%
  rownames_to_column()%>%
  mutate(q_V1_V2=visit_V1V2)%>%
  mutate(q_V1_V3V5=visit_V1_V3V5)%>%
  mutate(q_V1_V6V7=visit_V1_V6V7)%>%
  mutate(q_V1_V8V9=visitV1_V8V9)%>%
  mutate(ASV=rowname)%>%
  select(-c(1:9))

effect_size <- purrr::map2(effect_size_V1V2,effect_sizeV1_V3V5,cbind)
effect_size <- purrr::map2(effect_size,effect_size_V1_V6V7,cbind)
effect_size <- purrr::map2(effect_size,effect_size_V1_V8V9,cbind)

effect_size_df <- bind_rows(effect_size)
effect_size_df <- data.frame(effect_size_df$Ds)
effect_size_df  <- effect_size_df %>%
  rownames_to_column()%>%
  mutate(d_V1_V2=visit_V1V2)%>%
  mutate(d_V1_V3V5=visit_V1_V3V5)%>%
  mutate(d_V1_V6V7=visit_V1_V6V7)%>%
  mutate(d_V1_V8V9=visitV1_V8V9)%>%
  mutate(ASV=rowname)%>%
  select(-c(1:9))


status <- purrr::map2(status_V1V2,statusV1_V3V5,cbind)
status <- purrr::map2(status,status_V1_V6V7,cbind)
status <- purrr::map2(status,status_V1_V8V9,cbind)

status_df <- bind_rows(status)
status_df <- data.frame(status_df$status)
status_df  <- status_df %>%
  rownames_to_column()%>%
  mutate(status_V1_V2=visit_V1V2)%>%
  mutate(status_V1_V3V5=visit_V1_V3V5)%>%
  mutate(status_V1_V6V7=visit_V1_V6V7)%>%
  mutate(status_V1_V8V9=visitV1_V8V9)%>%
  mutate(ASV=rowname)%>%
  select(-c(1:9))

effect_table <- raw_p_df%>%
  full_join(corr_p_df, by="ASV")%>%
  full_join(effect_size_df, by="ASV")%>%
  full_join(status_df, by="ASV")%>%
  full_join(taxtable, by="ASV")

# select the entries which have OK_nc in status
effect_table_sig_order <- effect_table%>%
  filter(status_V1_V2=="OK_nc"|status_V1_V3V5=="OK_nc"|status_V1_V6V7 =="OK_nc" | status_V1_V8V9=="OK_nc")

#pivot long format

effect_table_sig_long_order <- effect_table_sig_order%>%
  pivot_longer(cols = starts_with("status"), names_to = "comparison_status", values_to = "status")%>%
  separate(comparison_status, c("variable","Visit1", "Visit_Sum"), "_")%>%
  mutate(comparison_status=paste(Visit1,Visit_Sum, sep="_"))%>%
  select(-c(variable, Visit1, Visit_Sum))%>%
  pivot_longer(cols = starts_with("p"), names_to = "comparison_p", values_to = "raw_p")%>%
  separate(comparison_p, c("variable","Visit1", "Visit_Sum"), "_")%>%
  mutate(comparison_p=paste(Visit1,Visit_Sum, sep="_"))%>%
  select(-c(variable, Visit1, Visit_Sum))%>%
  filter(comparison_p==comparison_status)%>%
  pivot_longer(cols = starts_with("d"), names_to = "comparison_effectSize", values_to = "effectSize")%>%
  separate(comparison_effectSize, c("variable","Visit1", "Visit_Sum"), "_")%>%
  mutate(comparison_effectSize=paste(Visit1,Visit_Sum, sep="_"))%>%
  select(-c(variable, Visit1, Visit_Sum))%>%
  filter(comparison_p==comparison_effectSize)%>%
  pivot_longer(cols = starts_with("q"), names_to = "comparison_q", values_to = "corr_p")%>%
  separate(comparison_q, c("variable","Visit1", "Visit_Sum"), "_")%>%
  mutate(comparison_q=paste(Visit1,Visit_Sum, sep="_"))%>%
  select(-c(variable, Visit1, Visit_Sum))%>%
  filter(comparison_p==comparison_q)%>%
  select(-c(comparison_q, comparison_effectSize,comparison_status))%>%
  mutate(fdr= as_factor(case_when(corr_p <= 0.05 ~ "*", corr_p <= 0.01 ~ "**", corr_p <= 0.001 ~ "***", corr_p <= 0.1 ~ ".")))%>%
  mutate(taxa= paste(Order, "(Order)"))%>%
  select(-Order)

```

```{r plot cuneiform order}
effect_table_sig_long_order%>%
  ggplot(aes (x = comparison_p, y = taxa))+ 
  geom_point (aes (fill = effectSize, shape = as.factor (sign (effectSize)), size = abs (effectSize), color=(fdr))) +
  scale_shape_manual (values = c (25, 24)) + 
  scale_fill_gradient2 (low = "blue", high = "red", mid = "white", midpoint = 0) +
  scale_color_manual(values=c("gray22","gray1","gray85"))+
  geom_text (aes (label = stars.pval (corr_p)))+
  theme_grey() +
  theme(axis.text.x = element_text(), #angle = 0, hjust = 0, vjust = 1
       legend.position = "right",axis.text.y = element_text(face = "italic"))+
  scale_x_discrete(labels=c("3", "6-12", "15-18", "21-24"))+
  labs(x= "months from treatment start")
```
There is no significant differences on phylum and class level -> omitted this code here

# Combine different tax levels into one plot
```{r Combine different tax levels into one plot, fig.width=12, fig.height=8}
# combine output tabels

effect_table_sig_all <- rbind(effect_table_sig_long, effect_table_sig_long_family, effect_table_sig_long_order)
write_csv(effect_table_sig_all, "~/Documents/Forschung/IMMProveCF/R_analysis/data/effect_size_table_sputum.csv")

p1 <- effect_table_sig_all%>%
  mutate(taxa_sep = taxa) %>%
  mutate(taxa = factor(taxa, levels = unique(taxa))) %>%
  ggplot(aes(x = comparison_p, y = taxa))+ 
  geom_point(aes(fill = effectSize, shape = as.factor (sign (effectSize)), size = abs (effectSize), color=(fdr))) +
  scale_size_continuous(name="Absolute effect size (Cliff's delta)") + 
  scale_shape_manual (name="",labels=c("decreased","increased"), values = c (25, 24)) + 
  scale_fill_gradient2(name= "Effect size", low = "#746999", high = "#69b3a2", mid = "white", midpoint = 0) +
  scale_color_manual(name="",labels=c(". fdr < 0.1", "* fdr < 0.05", "non-significant"), values=c("gray22","gray1","gray85"))+
  geom_text (aes (label = fdr))+
  theme_grey() +
  theme(axis.text.x = element_text(size=17),axis.title.x = element_text(size=17),#angle = 0, hjust = 0, vjust = 1
       legend.position = "right", axis.text.y = element_text(face = "italic", size=16),legend.text = element_text(size = 15),legend.title = element_text(size = 17),legend.key = element_rect(size = 8),
        legend.key.size = unit(1.5, 'lines'))+
  scale_x_discrete(labels=c("3", "6-12", "15-18", "21-24"))+
  labs(x= "months from treatment start", y="")#+
  #guides(shape = guide_legend(override.aes = list(size = 5)))
p1
ggsave("/Users/rebecca/Documents/Forschung/IMMProveCF/R_analysis/figures/relAb_cuneiform_plot_months.pdf", p1, width = 12, height = 7)

saveRDS(p1, "/Users/rebecca/Documents/Forschung/IMMProveCF/R_analysis/figures/relAb_cuneiform_sputum.rds")
```
```{r, fig.width=8, fig.height=6}
# improve figure for readibility
# Load required libraries
library(ggplot2)
library(dplyr)
library(gridExtra)

# Create the main plot
p1 <- effect_table_sig_all %>%   
  mutate(fdr= case_when(fdr=="."~"'", T~fdr)) %>% 
  mutate(taxa_sep = taxa) %>%
  mutate(taxa = factor(taxa, levels = unique(taxa))) %>%
  ggplot(aes(x = comparison_p, y = taxa)) + 
  geom_point(aes(fill = factor(sign(effectSize)), shape = factor(sign(effectSize)), size = abs(effectSize), color = fdr, alpha = 0.8)) +
  scale_size_continuous(name = "Absolute effect size") + 
  scale_shape_manual(name = "", labels = c("decreased", "increased"), values = c("-1" = 25, "1" = 24)) + 
  scale_fill_manual(name = "Effect size", 
                    values = c("-1" = "#746999", "1" = "#69b3a2"),
                    labels = c("decreased", "increased")) +
  scale_color_manual(name = "", labels = c(" fdr < 0.1", "* fdr < 0.05", "non-significant"), values = c("gray22", "gray1", "gray85")) +
  geom_text(aes(label = fdr), size=8, nudge_y = -0.2) +
  theme_pubclean(base_size = 14) +
  theme(
    legend.position = "none",
    axis.text.x = element_text(size=14),
    axis.text.y = element_text(size=14, face = "italic"),
    legend.key = element_rect(size = 12),
    legend.key.size = unit(1.5, 'lines')
  ) +
  scale_x_discrete(labels = c("3", "6-12", "15-18", "21-24")) +
  labs(x = "months from treatment start", y = "")
p1

p1+theme(legend.position = "bottom")
```

# create a better legend
```{r, fig.width=8, fig.height=8}

# Extract the legend
get_legend <- function(p) {
  tmp <- ggplot_gtable(ggplot_build(p))
  leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
  legend <- tmp$grobs[[leg]]
  return(legend)
}

# Create a plot with only the size legend and convert circles to triangles
size_legend <- effect_table_sig_all %>%
  ggplot(aes(x = comparison_p, y = taxa)) + 
  geom_point(aes(size = abs(effectSize), fill = factor(sign(effectSize)), shape = factor(sign(effectSize)),color = fdr, alpha = 0.8), shape = 24) + 
  scale_size_continuous(name = "Absolute effect size (Cliff's delta)") +
  scale_fill_manual(name = "Effect size", 
                    values = c("-1" = "#746999", "1" = "#69b3a2"),
                    labels = c("decreased", "increased")) +
  scale_shape_manual(name = "", labels = c("decreased", "increased"), values = c("-1" = 25, "1" = 24)) +
  #scale_color_manual(name = "", labels = c(". fdr < 0.1", "* fdr < 0.05", "non-significant"), values = c("gray22", "gray1", "gray85")) +
  theme_void() +
  theme(
    legend.position = "bottom",
    legend.title = element_text(size = 10),
    legend.text = element_text(size = 10)
  )+
  guides(alpha = "none") 

# Extract the size legend
size_legend <- get_legend(size_legend)

# Combine the main plot and the size legend
grid.arrange(p1, size_legend, ncol = 2, nrow=1, widths = c(3, 1))
da_sputum <- as_ggplot(grid.arrange(p1, size_legend, ncol = 1, nrow=2, heights = c(4, 1)))

saveRDS(p1, "/Users/rebecca/Documents/Forschung/IMMProveCF/R_analysis/figures/da_sputum_woLegend.rds")

saveRDS(da_sputum, "/Users/rebecca/Documents/Forschung/IMMProveCF/R_analysis/figures/da_sputum.rds")
grid.arrange(size_legend)
```


```{r combine sputum and stool results, fig.width=12, fig.height=8}

effect_table_sig_all_stool <- read_csv("~/Documents/Forschung/IMMProveCF/R_analysis/data/effect_size_table_stool.csv")

effect_table_sig_all_stool$material <- c("stool")
effect_table_sig_all$material <- c("sputum")

effect_table_sig_sputum_stool <- rbind(effect_table_sig_all, effect_table_sig_all_stool)

effect_table_sig_sputum_stool%>%
  ggplot(aes(x = comparison_p, y = taxa))+ 
  geom_point(aes(fill = effectSize, shape = as.factor (sign (effectSize)), size = abs (effectSize), color=(fdr))) +
  scale_size_continuous(name="Absolute effect size (Cliff's delta)") + 
  scale_shape_manual (name="",labels=c("increased", "decreased"), values = c (25, 24)) + 
  scale_fill_gradient2(name= "Effect size (Cliff's delta)", low = "#746999", high = "#69b3a2", mid = "white", midpoint = 0) +
  scale_color_manual(name="",labels=c(". fdr < 0.1", "* fdr < 0.05", "non-significant"), values=c("gray22","gray1","gray85"))+
  geom_text (aes (label = fdr))+
  theme_grey() +
  theme(axis.text.x = element_text(size=17),axis.title.x = element_text(size=17),#angle = 0, hjust = 0, vjust = 1
       legend.position = "right", axis.text.y = element_text(face = "italic", size=16),legend.text = element_text(size = 15),legend.title = element_text(size = 17),legend.key = element_rect(size = 8),
        legend.key.size = unit(1.5, 'lines'))+
  scale_x_discrete(labels=c("3", "6-12", "15-18", "21-24"))+
  labs(x= "months from treatment start", y="")+
  facet_grid(rows=vars(material), scales = "free", space = "free")

ggsave("/Users/rebecca/Documents/Forschung/IMMProveCF/R_analysis/figures/relAb_cuneiform_plot_months_sputumAndstool.pdf", width = 12, height = 7)
```

