---
title: "Combine sputum plot"
author: "Rebecca L. Knoll"
date: "`r Sys.Date()`"
output: html_document
---

```{r run import script, include=FALSE}
# run script to tidy the data and to load packages, create phyloseq object (ps_clean) and load libraries
#install.packages("ggplot2")
#install.packages("gridExtra")
pacman::p_load(tidyverse, phyloseq, magrittr, janitor, microbiome, microViz, knitr, lubridate, naniar, readxl, ggplot2, ggpubr, ggalluvial, metadeconfoundR)

#pacman::p_load(rmarkdown, tidyverse, phyloseq, magrittr, janitor, microbiome, knitr, lubridate, naniar, readxl, ggplot2, ggpubr,rstatix, metadeconfoundR, microViz)

library(gridExtra)
library(scales)
```

# read figures from rds files
```{r}
dom_spu <- readRDS("/Users/rebecca/Documents/Forschung/IMMProveCF/R_analysis/figures/alluvial_dominantGenus.rds")
tax_sputum <- readRDS("/Users/rebecca/Documents/Forschung/IMMProveCF/R_analysis/figures/da_sputum.rds")
tax_sputum_woLegend <- readRDS("/Users/rebecca/Documents/Forschung/IMMProveCF/R_analysis/figures/da_sputum_woLegend.rds")
metad_sputum <-  readRDS("/Users/rebecca/Documents/Forschung/IMMProveCF/R_analysis/figures/sputum_metad.rds")
staph <- readRDS("/Users/rebecca/Documents/Forschung/IMMProveCF/R_analysis/figures/cor_staph_chloride_sputum.rds")
hm_div_sputum <- readRDS("/Users/rebecca/Documents/Forschung/IMMProveCF/R_analysis/figures/hm_div_sputum.rds")
star <- readRDS("/Users/rebecca/Documents/Forschung/IMMProveCF/R_analysis/figures/starplot_sputum.rds")
permanova_bubble <- readRDS("/Users/rebecca/Documents/Forschung/IMMProveCF/R_analysis/rds_files/PERMANOVA_timepoints_sputum.rds")
permanova_univariate <- readRDS("/Users/rebecca/Documents/Forschung/IMMProveCF/R_analysis/rds_files/sputum_univariate_permanova_stratified.rds")
permanova_combined<- readRDS("/Users/rebecca/Documents/Forschung/IMMProveCF/R_analysis/rds_files/sputum_combined_permanova_stratified_31Samples:withoutETI.rds")
permanova_barplot_2 <- readRDS("/Users/rebecca/Documents/Forschung/IMMProveCF/R_analysis/rds_files/sputum_combined_permanova_barplot.rds")

sputum_shannon<- readRDS("/Users/rebecca/Documents/Forschung/IMMProveCF/R_analysis/figures/sputum_shannon.rds")
sputum_observed <- readRDS("/Users/rebecca/Documents/Forschung/IMMProveCF/R_analysis/figures/sputum_observed.rds")

sputum_barplot <- readRDS("/Users/rebecca/Documents/Forschung/IMMProveCF/R_analysis/figures/sputum_barplot.rds")

sputum_lolli <- readRDS("/Users/rebecca/Documents/Forschung/IMMProveCF/R_analysis/rds_files/sputum_permanova_lollipop_plot.rds")
```

# upload pdf/png files
```{r}
library(png)
img <- readPNG("/Users/rebecca/Documents/Forschung/IMMProveCF/Manuscript_16S/IMMProveCF_public/figures/sweat_chloride_mediation_crop.png")

# Convert it to a grob
library(grid)
g <- rasterGrob(img)

# Use gridExtra to arrange it
library(gridExtra)
g <- grid.arrange(g)
g <- as_ggplot(g)
img2 <- readPNG("/Users/rebecca/Documents/Forschung/IMMProveCF/Manuscript_16S/IMMProveCF_public/figures/IC_25_plot_Annes_Version.png")
ic25 <- rasterGrob(img2)
ic25 <- grid.arrange(ic25)
ic25 <- as_ggplot(ic25)
ic25 <- ic25+ theme(axis.text= element_text(size = 14), legend.title.position = "top", axis.title = element_text(size=14), legend.text = element_text(size = 14), legend.title =  element_text(size = 14))

#ic <- readRDS("/Users/rebecca/Documents/Forschung/IMMProveCF/Manuscript_16S/IC25_figure/IC25_Annes_Version.rds")
```

# harmonize font size
```{r}
dom_palette <- c(
  Streptococcus = "#69b3a2", 
  Staphylococcus = "#E55E00", 
  Fusobacterium = "#6FB899FF", 
  Prevotella_7 = "#31A1B3FF", 
  Rothia = "#027B8EFF", 
  Pseudomonas = "#EE6AA7", 
  Eikenella = "#94D0C0FF", 
  Haemophilus = "#CCB22BFF", 
  Achromobacter = "#9F8F14FF", 
  Gemella = "#97CFD0", 
  Moraxella = "#6FB899", 
  `missing sample` = "#CFCFCF"
)

dom_palette_labels <- c(
  Streptococcus = "Streptococcus",
  Staphylococcus = "Staphylococcus",
  Fusobacterium = "Fusobacterium",
  Prevotella_7 = "Prevotella 7",
  Rothia = "Rothia",
  Pseudomonas = "Pseudomonas",
  Eikenella = "Eikenella",
  Haemophilus = "Haemophilus",
  Achromobacter = "Achromobacter",
  Gemella = "Gemella",
  Moraxella = "Moraxella",
  `missing sample` = "no sample"
)

dom_spu <- dom_spu +
  theme(text = element_text(size = 14), 
        legend.text = element_text(size = 14), legend.title.position = "top") +
  guides(fill = guide_legend(nrow = 4, position = "top", 
                             label.theme = element_text(angle = 0, face = "italic", size = 14))) +
  scale_fill_manual(values = dom_palette, labels= dom_palette_labels)


tax_sputum <- tax_sputum+theme(legend.text = element_text(size = 14))

star <- star + theme(axis.text= element_text(size = 14), legend.title.position = "top", legend.position = "top", axis.title = element_text(size=14), legend.text = element_text(size = 14), legend.title =  element_text(size = 14))

sputum_lolli <- sputum_lolli+ theme(axis.text= element_text(size = 14), axis.title = element_text(size=14), legend.text = element_text(size = 14), legend.title =  element_text(size = 14), legend.title.position = "left",  legend.position = "top")+ 
 guides(color=guide_legend(nrow = 2, position = "top")) 

metad_sputum <- metad_sputum + theme(axis.text.x=element_text(size=14, angle = 40, hjust = 1, vjust = 1.05), axis.text.y=element_text(size=14, face="italic"), legend.title = element_text(size=14), legend.position = "bottom")
  
hm_div_sputum <- hm_div_sputum + theme(legend.position = "bottom", text = element_text(size = 14), legend.box = "horizontal") + scale_fill_gradient2(name= "Effect size\n(Cliff's delta)", low = "#746999", high = "#69b3a2", mid = "white", midpoint = 0, guide = guide_colorbar(raster = F),labels = scales::number_format(accuracy = 0.1))+
  guides(title.position = "left")

staph <- staph +theme(text = element_text(size = 14),legend.text = element_text(size = 14), axis.text = element_text(size = 14), axis.title = element_text(size=14), legend.title =  element_text(size = 14), legend.position = "right")+ guides(color=guide_legend(nrow = 5, title = "Month from \ntreatment start")) 

sputum_observed <- sputum_observed+theme(text = element_text(size = 14))
sputum_shannon <- sputum_shannon+theme(text = element_text(size = 14))
sputum_barplot <- sputum_barplot+theme(text = element_text(size = 14))

permanova_bubble <- permanova_bubble + theme(legend.position = "top", legend.title.position = "top", text = element_text(size = 14)) + guides(fill = guide_legend(ncol = 1), size=guide_legend(nrow = 2)) 

```

```{r, fig.width=16, fig.height=14}
library(ggplot2)
library(scales)

grid_arranged <- grid.arrange(
  star+ggtitle("") + labs(tag = "a"), #1
  permanova_bubble +labs(tag = "b"), #2
  dom_spu+ labs(tag = "c"), #3
  sputum_lolli + labs(tag = "d"), #4
  staph+ labs(tag = "e"), #5
  g + labs(tag = "f"), #6
  ic25 + labs(tag = "g"), #7
 
  ncol = 3, nrow = 3,
  heights = c(1.2, 1, 1),
  widths=c(1,1,1),
  layout_matrix = rbind(c(1,2,3),
                        c(4,5,6),
                        c(7,7,7))
                       )

# Print or save the arranged plot
print(grid_arranged)
ggsave("/Users/rebecca/Documents/Forschung/IMMProveCF/Manuscript_16S/sputum_figure_12032024.png",grid_arranged, dpi = 300, width = 16, height = 14)

ggsave("/Users/rebecca/Documents/Forschung/IMMProveCF/Manuscript_16S/sputum_figure_12032024.pdf",grid_arranged, dpi = 300, width = 16, height = 14)
```

```{r, fig.width=16, fig.height=24}
library(ggplot2)
library(scales)

grid_arranged <- grid.arrange(
  star+ggtitle("") + labs(tag = "a"), #1
  permanova_bubble + theme(legend.position = "bottom", legend.title.position = "left") + guides(fill = guide_legend(nrow = 3), size=guide_legend(nrow = 2))  +labs(tag = "b"), #2
  dom_spu+theme(legend.position = "bottom", legend.title.position = "top") + guides(fill = guide_legend(nrow = 4)) + labs(tag = "c"), #3
  permanova_barplot_2 +  labs(tag = "d"), #4
  metad_sputum + ggtitle("") + labs(tag = "e"), #5
  staph+ labs(tag = "f"), #6
  g + labs(tag = "g"), #7
  ic25 + labs(tag = "h"), #8
 
  ncol = 3, nrow = 5,
  heights = c(1.2, 1.2, 1, 1, 1),
  widths=c(1,1,1.2),
  layout_matrix = rbind(c(1,2,3),
                        c(4,5,5),
                        c(6,5,5),
                        c(7,5,5),
                        c(8,8,8))
                       )

# Print or save the arranged plot
print(grid_arranged)
ggsave("/Users/rebecca/Documents/Forschung/IMMProveCF/Manuscript_16S/sputum_figure_11122024.png",grid_arranged, dpi = 300, width = 16, height = 24)
```
```{r, fig.width=16, fig.height=24}
library(ggplot2)
library(scales)

grid_arranged <- grid.arrange(
  star+ggtitle("") + labs(tag = "a"), #1
  permanova_bubble+labs(tag = "b"), #2
  dom_spu + theme(legend.position = "bottom")+ labs(tag = "c"), #3
  permanova_barplot_2+theme(legend.position = "right") +  labs(tag = "d"), #4
  metad_sputum + ggtitle("") + labs(tag = "e"), #5
  staph+ labs(tag = "f"), #6
  g + labs(tag = "g"), #7
  ic25 + labs(tag = "h"), #8
 
  ncol = 6, nrow = 5,
  #heights = c(1, 1, 1.5, 1, 1),
  widths=c(1,1.5,1,1,1,1),
  layout_matrix = rbind(c(1,1,1,2,2,2),
                        c(3,3,5,5,5,5),
                        c(4,4,5,5,5,5),
                        c(6,6,6,7,7,7),
                        c(8,8,8,8,8,8))
                       )

# Print or save the arranged plot
print(grid_arranged)
```

```{r, fig.width=16, fig.height=24}
library(ggplot2)
library(scales)

grid_arranged <- grid.arrange(
  star+ggtitle("") + labs(tag = "a"), #1
  permanova_bubble+labs(tag = "b"), #2
  permanova_univariate +  labs(tag = "d"), #3
  permanova_combined +  labs(tag = "e"), #4
  dom_spu + labs(tag = "c"), #5
  metad_sputum + ggtitle("") + labs(tag = "f"), #6
  staph+ labs(tag = "g"), #7
  g + labs(tag = "h"), #8
  ic25 + labs(tag = "i"), #9
 
  ncol = 5, nrow = 5,
  heights = c(1, 1, 1.5, 1, 1),
 # widths=c(1,1,0.5),
  layout_matrix = rbind(c(1,1,5,5,5),
                        c(2,2,3,3,4),
                        c(6,6,6,7,7),
                        c(6,6,6,8,8),
                        c(9,9,9,9,9))
                       )

# Print or save the arranged plot
print(grid_arranged)

#ggsave("/Users/rebecca/Documents/Forschung/IMMProveCF/Manuscript_16S/sputum_figure_11122024.png",grid_arranged, dpi = 300, width = 16, height = 24)
```

```{r, fig.width=16, fig.height=20}
library(ggplot2)
library(scales)

grid_arranged <- grid.arrange(
  star+ggtitle("") + labs(tag = "A"), #1
  permanova_bubble+labs(tag = "B"), #2
  permanova_univariate +  labs(tag = "D"), #3
  permanova_combined +  labs(tag = "E"), #4
  dom_spu + labs(tag = "C"), #5
  metad_sputum + ggtitle("") + labs(tag = "F"), #6
  staph+ labs(tag = "G"), #7
  g + labs(tag = "H"), #8
  ic25 + labs(tag = "I"), #9
 
  ncol = 3, nrow = 5,
  heights = c(1, 1, 1, 1.5, 1),
  widths=c(1,1,0.5),
  layout_matrix = rbind(c(1,5,5),
                        c(2,3,4),
                        c(6,6,7),
                        c(6,6,8),
                        c(9,9,9))
                       )

# Print or save the arranged plot
print(grid_arranged)

```

```{r, fig.width=16, fig.height=20}
library(ggplot2)
library(gridExtra)
library(ggalluvial)

grid_arranged <- grid.arrange(
  dom_spu + labs(tag = "A") ,
  tax_sputum + labs(tag = "B") ,
  metad_sputum + labs(tag = "C") +ggtitle(""),
  ic + labs(tag = "F"),
  hm_div_sputum + labs(tag = "E"),
  staph+ labs(tag = "D"),
  ncol = 4, nrow = 4,
  heights = c(0.75, 1.5, 1, 1),
  widths=c(1.25,1.25,1.5,1.5),
  layout_matrix = rbind(c(1,1,3,3),
                        c(2,2,3,3),
                        c(6,5,3,3),
                        c(4,4,4,4))
                       )

# Print or save the arranged plot
print(grid_arranged)

#ggsave("/Users/rebecca/Documents/Forschung/IMMProveCF/Manuscript_16S/sputum_figure.png",grid_arranged, dpi = 300, width = 16, height = 20)
```
# Supplementary figure for sputum
```{r, fig.height=8, fig.width=8}

grid_arranged <- grid.arrange(
  sputum_shannon + labs(tag = "a") ,
  sputum_observed + labs(tag = "b") ,
  tax_sputum_woLegend + labs(tag = "c"), #+ggtitle(""),
  hm_div_sputum + labs(tag = "d"),
  ncol = 2, nrow = 3,
  heights = c(1, 1, 1.5),
  widths=c(1,1.75),
  layout_matrix = rbind(c(1,3),
                        c(2,3),
                        c(4,3))
                       )

```
```{r, fig.height=12, fig.width=6}
sputum_barplot
grid_arranged <- grid.arrange(
  sputum_shannon + labs(tag = "a") ,
  sputum_observed + labs(tag = "b") ,
  tax_sputum_woLegend + labs(tag = "c"), #+ggtitle(""),
  NULL,
  hm_div_sputum + labs(tag = "d") + theme(legend.position = "right"),
  ncol = 2, nrow = 4,
  heights = c(0.95, 1.75, 0.25, 1),
  #widths=c(1,1.75),
  layout_matrix = rbind(c(1,2),
                        c(3,3),
                        c(4,4),
                        c(5,5))
                       )
ggsave("/Users/rebecca/Documents/Forschung/IMMProveCF/Manuscript_16S/sputum_figure_supp.png",grid_arranged, dpi = 300, width = 6, height = 12)
```

```{r, fig.height=18, fig.width=16}
grid_arranged <- grid.arrange(
  sputum_shannon + labs(tag = "a") ,
  sputum_observed + labs(tag = "b") ,
  metad_sputum + labs(tag = "c") +ggtitle(""),
  tax_sputum + labs(tag = "d"), #+ggtitle(""),
  hm_div_sputum + labs(tag = "e") + theme(legend.position = "right"),
  sputum_barplot+theme(legend.position = "bottom"), 
  ncol = 3, nrow = 4,
  heights = c(0.75, 1.2, 0.65, 1),
  widths=c(1,1,2.5),
  layout_matrix = rbind(c(1,2,3),
                        c(4,4,3),
                        c(5,5,3),
                        c(6,6,6))
                       )
ggsave("/Users/rebecca/Documents/Forschung/IMMProveCF/Manuscript_16S/041224_sputum_figure_supp.png",grid_arranged, dpi = 300, width = 16, height = 18)

ggsave("/Users/rebecca/Documents/Forschung/IMMProveCF/Manuscript_16S/Revision/pdf_figures/supp_figure2.pdf",grid_arranged, dpi = 300, width = 16, height = 18)
```
