---
title: "stool figure"
author: "Rebecca L. Knoll"
date: "`r Sys.Date()`"
output: html_document
---

```{r run import script, include=FALSE}
# run script to tidy the data and to load packages, create phyloseq object (ps_clean) and load libraries
#install.packages("ggplot2")
#install.packages("gridExtra")
pacman::p_load(tidyverse, phyloseq, magrittr, janitor, microbiome, microViz, knitr, lubridate, naniar, readxl, ggplot2, ggpubr, ggalluvial, metadeconfoundR)

#pacman::p_load(rmarkdown, tidyverse, phyloseq, magrittr, janitor, microbiome, knitr, lubridate, naniar, readxl, ggplot2, ggpubr,rstatix, metadeconfoundR, microViz)

library(gridExtra)
library(scales)
library(ggplot2)
library(metadeconfoundR)

packageVersion("ggplot2")
library(dplyr)
library(gridExtra)
library(scales)
remotes::install_version("ggplot2", version = "3.1.0")
library(ggplot2)
```

# read figures from rds files
```{r}
tax_stool <- readRDS("/Users/rebecca/Documents/Forschung/IMMProveCF/R_analysis/figures/relAb_cuneiform_plot_stool_patients.rds")
tax_stool

tax_stool_legend <- readRDS("/Users/rebecca/Documents/Forschung/IMMProveCF/R_analysis/figures/da_stool.rds")
tax_stool_legend

metad_stool <-  readRDS("/Users/rebecca/Documents/Forschung/IMMProveCF/Manuscript_16S/IMMProveCF_public/outputs/stool_metaD_25percentprevalence.rds")
metad_stool

cor <- readRDS("/Users/rebecca/Documents/Forschung/IMMProveCF/Manuscript_16S/IMMProveCF_public/outputs/cor_esch_cale_stool.rds")
cor

hm_div_stool <- readRDS("/Users/rebecca/Documents/Forschung/IMMProveCF/Manuscript_16S/IMMProveCF_public/outputs/stool_div_hm.rds")
hm_div_stool

star <- readRDS("/Users/rebecca/Documents/Forschung/IMMProveCF/R_analysis/figures/starplot_stool.rds")
star <- star+ggtitle("")

stool_shannon <- readRDS("/Users/rebecca/Documents/Forschung/IMMProveCF/R_analysis/figures/stool_shannon.rds")
stool_observed <- readRDS("/Users/rebecca/Documents/Forschung/IMMProveCF/R_analysis/figures/stool_observed.rds")

bubble<-  readRDS("/Users/rebecca//Documents/Forschung/IMMProveCF/R_analysis/rds_files/PERMANOVA_timepoints_stool_woControls.rds")

stool_combined_permanova_barplot <- readRDS("/Users/rebecca/Documents/Forschung/IMMProveCF/R_analysis/rds_files/stool_combined_permanova_barplot.rds")

lolli <- readRDS("/Users/rebecca/Documents/Forschung/IMMProveCF/R_analysis/rds_files/stool_permanova_lollipop_plot.rds")
```

# harmonize font size
```{r}
metad_stool <- metad_stool+ theme(axis.text.x=element_text(size=12, angle = 40, hjust = 1, vjust = 1.05), axis.text.y=element_text(size=12, face="italic"), legend.title = element_text(size=12), legend.position = "bottom")

hm_div_stool <- hm_div_stool+ theme(axis.text.x=element_text(size=12, angle = 40, hjust = 1, vjust = 1.05), axis.text.y=element_text(size=12, face="italic"), legend.title = element_text(size=12), legend.position = "bottom")

tax_stool_legend <- tax_stool_legend+ theme(axis.text.x=element_text(size=12, angle = 40, hjust = 1, vjust = 1.05), axis.text.y=element_text(size=12, face="italic"), legend.title = element_text(size=12), legend.position = "bottom")

cor <- cor + theme(axis.text.x=element_text(size=12, angle = 40, hjust = 1, vjust = 1.05), axis.text.y=element_text(size=12, face="italic"), legend.title = element_text(size=12), legend.position = "bottom")

bubble <- bubble+ theme(legend.position = "bottom", legend.title.position = "left") + guides(fill = guide_legend(nrow = 4), size=guide_legend(nrow = 2))  +labs(tag = "b")
```
# arrange figure
```{r, fig.width=16, fig.height=10}

library(gridExtra)

grid_arranged <- grid.arrange(
  tax_stool_legend + labs(tag = "A") ,
  metad_stool + labs(tag = "B") ,
  hm_div_stool + labs(tag = "D"),
  cor+ labs(tag = "C"),
  ncol = 4, nrow = 4,
  heights = c(1, 1, 0.75, 0.75),
  widths=c(1.25,1.15,1.5,1.5),
  layout_matrix = rbind(c(1,1,2,2),
                        c(1,1,2,2),
                        c(4,3,2,2),
                        c(4,3,2,2))
                       )

# Print or save the arranged plot
print(grid_arranged)

#ggsave("/Users/rebecca/Documents/Forschung/IMMProveCF/Manuscript_16S/stool_figure.png",grid_arranged, dpi = 300, width = 16, height = 10)
```

```{r, fig.width=16, fig.height=12}

library(gridExtra)

grid_arranged <- grid.arrange(
  star+ labs(tag = "a") ,
  bubble + labs(tag = "b") ,
  stool_combined_permanova_barplot+ labs(tag = "c"),
  hm_div_stool+ labs(tag = "d"),
  metad_stool+ labs(tag = "e"),
  cor+ labs(tag = "f"),
  ncol = 3, nrow = 3,
  heights = c(1.25, 1 , 1.25),
  widths=c(0.9,1,1.3),
  layout_matrix = rbind(c(1,2,3),
                        c(4,5,5),
                        c(6,5,5))
                       )

# Print or save the arranged plot
print(grid_arranged)

ggsave("/Users/rebecca/Documents/Forschung/IMMProveCF/Manuscript_16S/stool_figure2.png",grid_arranged, dpi = 300, width = 16, height = 12)
```

```{r, fig.width=16, fig.height=10}

library(gridExtra)

grid_arranged <- grid.arrange(
  star+ labs(tag = "a") ,
  bubble + labs(tag = "b") ,
  lolli+ labs(tag = "c"),
  hm_div_stool+ labs(tag = "d"),
  cor+ labs(tag = "e"),
  NULL, 
  ncol = 3, nrow = 2,
  heights = c(1.1, 1),
  widths=c(0.9,1,1.3),
  layout_matrix = rbind(c(1,2,3),
                        c(4,5,6)
                       ))

# Print or save the arranged plot
print(grid_arranged)

ggsave("/Users/rebecca/Documents/Forschung/IMMProveCF/Manuscript_16S/stool_figure3.png",grid_arranged, dpi = 300, width = 16, height = 10)
```

# Supplementary figure
```{r, fig.width=16, fig.height=10}

grid_arranged <- grid.arrange(
  stool_shannon + labs(tag = "a") ,
 stool_observed + labs(tag = "b") ,
 metad_stool+ labs(tag = "c") ,
  tax_stool_legend+ labs(tag = "d"),
  ncol = 3, nrow = 2,
  heights = c(1 , 1.5),
  widths=c(0.5,0.5,1),
  layout_matrix = rbind(c(1,2,3),
                        c(4,4,3))
                       )

# Print or save the arranged plot
print(grid_arranged)

ggsave("/Users/rebecca/Documents/Forschung/IMMProveCF/Manuscript_16S/stool_supplement_figure.png",grid_arranged, dpi = 300, width = 16, height = 10)
```