---
title: "Plot sample number in upsetPlots"
author: "Rebecca L. Knoll"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load libraries and run functions script}
library(microViz)

pacman::p_load(tidyverse, phyloseq, magrittr, janitor, microbiome, knitr, lubridate, naniar, readxl, ggplot2, ggpubr)

library("pheatmap")
library(dendextend)
library(vegan)
library(ComplexUpset) # excellent tutorial: https://krassowski.github.io/complex-upset/articles/Examples_R.html

ps_full <- readRDS("/Users/rebecca/Documents/Forschung/IMMProveCF/R_analysis/rds_files/ps_IMProveCF_patientsAndControls_Run1-23_18102023.rds")

ps_full_relab <- transform_sample_counts(ps_full, function(x) x/sum(x)*100)

#extract metadata
metadata<- as(sample_data(ps_full),"data.frame")

```

# Sputum
```{r}
metadata <- metadata %>% 
  filter(project=="IMP") 

#  DataFrame setup
count_df <-  metadata%>%
  filter(material == "Sputum") %>% 
    tabyl(id.x, visit_cal_cor) 

count_df <- clean_names(count_df) %>% 
  rename_with(~ str_replace_all(., "^x", "Visit"), starts_with("x"))
  
# plot
p1 <- ComplexUpset::upset(data=count_df, intersect= c("Visit1", "Visit2", "Visit3", "Visit4", "Visit5", "Visit6", "Visit7", "Visit8", "Visit9"), min_size=1, width_ratio=0.2, height_ratio=1, sort_sets=FALSE, stripes=c("darkgrey",  "#C3BC3FFF", "#6388B4FF", "#6388B4FF", "#6388B4FF","#BB7693FF","#BB7693FF","#55AD89FF","#55AD89FF"))
sputum <- p1 + ggtitle('Sputum samples')
sputum

#Extract plot data to find intersection coordinates
p1_data <- ggplot_build(p1)$data[[2]]  # Layer 2 usually contains the intersection points

# Add a white plus sign to the black dots
sputum <- p1 +
  geom_point(
    data = p1_data,  # Extract the data from the ComplexUpset plot
    aes(x = x, y = y),
    shape = 3,       # Shape 3 is a plus sign
    size = 1.5,        # Adjust size of the plus sign
    color = "lightgrey", # Make the plus sign white
    stroke = 1       # Adjust stroke width
  ) +
  ggtitle('Sputum samples')

sputum
```

# Throat
```{r}
metadata <- metadata %>% 
  filter(project=="IMP") 

#  DataFrame setup
count_df <-  metadata%>%  
  filter(material == "Throat")%>%
    tabyl(id.x, visit_cal_cor) 

count_df <- clean_names(count_df) %>% 
  rename_with(~ str_replace_all(., "^x", "Visit"), starts_with("x"))
  
# plot
p1 <- ComplexUpset::upset(data=count_df, intersect= c("Visit1", "Visit2", "Visit3", "Visit4", "Visit5", "Visit6", "Visit7", "Visit8", "Visit9"), min_size=1, width_ratio=0.2, height_ratio=1, sort_sets=FALSE, stripes=c("darkgrey",  "#C3BC3FFF", "#6388B4FF", "#6388B4FF", "#6388B4FF","#BB7693FF","#BB7693FF","#55AD89FF","#55AD89FF"))


#Extract plot data to find intersection coordinates
p1_data <- ggplot_build(p1)$data[[2]]  # Layer 2 usually contains the intersection points

# Add a white plus sign to the black dots
throat <- p1 +
  geom_point(
    data = p1_data,  # Extract the data from the ComplexUpset plot
    aes(x = x, y = y),
    shape = 3,       # Shape 3 is a plus sign
    size = 1.5,        # Adjust size of the plus sign
    color = "lightgrey", # Make the plus sign white
    stroke = 1       # Adjust stroke width
  ) +
  ggtitle('Throat samples')

throat
```

# Stool
```{r}
metadata <- metadata %>% 
  filter(project=="IMP") 

#  DataFrame setup
count_df <-  metadata%>%  
  filter(material == "Stool")%>%
    tabyl(id.x, visit_cal_cor) 

count_df <- clean_names(count_df) %>% 
  rename_with(~ str_replace_all(., "^x", "Visit"), starts_with("x"))
  
# plot
p1 <- ComplexUpset::upset(data=count_df, intersect= c("Visit1", "Visit2", "Visit3", "Visit4", "Visit5", "Visit6", "Visit7", "Visit8", "Visit9"), min_size=1, width_ratio=0.2, height_ratio=1, sort_sets=FALSE, stripes=c("darkgrey",  "#C3BC3FFF", "#6388B4FF", "#6388B4FF", "#6388B4FF","#BB7693FF","#BB7693FF","#55AD89FF","#55AD89FF"))
stool <- p1 + ggtitle('Stool samples')

 #Extract plot data to find intersection coordinates
p1_data <- ggplot_build(p1)$data[[2]]  # Layer 2 usually contains the intersection points

# Add a white plus sign to the black dots
stool <- p1 +
  geom_point(
    data = p1_data,  # Extract the data from the ComplexUpset plot
    aes(x = x, y = y),
    shape = 3,       # Shape 3 is a plus sign
    size = 1.5,        # Adjust size of the plus sign
    color = "lightgrey", # Make the plus sign white
    stroke = 1       # Adjust stroke width
  ) +
  ggtitle("Stool samples")

stool


```

# plot 16S library size 
```{r}
visit_sum_palette <- c("black", "#C3BC3FFF", "#6388B4FF", "#BB7693FF", "#55AD89FF", "#8176AA")

metadata<- as(sample_data(ps_full),"data.frame")
metadata$visit_sum

metadata<-metadata %>% 
  mutate(visit_sum=case_when(visit_sum=="8-10"~"8-9", T~visit_sum))
metadata$visit_sum

visit_sum_labels <- c("0", "3", "6-12", "15-18", "21-24", "Control")
d <- metadata %>% 
  ggplot(aes(material, total_reads, fill = visit_sum)) +
  geom_boxplot(alpha = 0.65) +
  scale_fill_manual(values = visit_sum_palette, labels = visit_sum_labels) +  # Corrected part
  scale_y_log10() +
  theme_bw() +
  theme(legend.position = "none", text = element_text(size = 16)) +
  labs(x = "", y = "Library size", fill = "Months from treatment start")
d

legend <- get_legend(d+theme(legend.position = "bottom", legend.title.position = "top"))

legend2 <- get_legend(d + 
                        theme(legend.position = "bottom", legend.title.position = "left")+ 
                        guides(fill = guide_legend(nrow = 1)))

saveRDS(legend2, "/Users/rebecca/Documents/Forschung/IMMProveCF/R_analysis/figures/legend_visit_sum.rds")
as_ggplot(legend2)

summary(lmsummary(lmsummary(lmerTest::lmer(total_reads ~ visit_sum + + (1|material) + (1|id.x), data=metadata))
kruskal.test(total_reads ~ visit_sum, data=metadata)

summary(lmerTest::lmer(total_reads ~ material + (1|id.x), data=metadata))
kruskal.test(total_reads ~ material, data=metadata)
```
```{r}

e<- metadata %>% 
  ggplot(aes(material, quantity_mean, fill=visit_sum))+
  geom_boxplot(alpha=0.65) +
  scale_fill_manual(values = visit_sum_palette)+
  scale_y_log10()+
  theme_bw()+
  theme(legend.position = "none", text = element_text(size = 16))+
  labs(x="", y="16S copy number", fill="Visits")
e

summary(lmerTest::lmer(quantity_mean ~ visit_sum + (1|material) + (1|id.x), data=metadata))
kruskal.test(quantity_mean ~ visit_sum, data=metadata)

summary(lmerTest::lmer(quantity_mean ~ material + (1|id.x), data=metadata))
kruskal.test(quantity_mean ~ material, data=metadata)
```

```{r, fig.height=20, fig.width=16}

clin_evol <- readRDS("/Users/rebecca/Documents/Forschung/IMMProveCF/R_analysis/figures/clinical_evolution.rds")

samples <- ggarrange(sputum, throat, stool, labels = c("a", "b", "c"), nrow = 1)

bio <- ggarrange(e, d, legend,labels = c("p", "q"), nrow = 1)

ggarrange(samples, clin_evol, bio, nrow = 3, ncol=1, heights = c(0.5,1.15,0.35))
ggsave("/Users/rebecca/Documents/Forschung/IMMProveCF/R_analysis/figures/supp_fig1_clinevol_upsetplots.png", height = 20, width = 16)

ggsave("/Users/rebecca/Documents/Forschung/IMMProveCF/Manuscript_16S/pdf_figures/supp_fig1_clinevol_upsetplots.pdf", height = 20, width = 16)

```
